name: 'GHA k3s'
author: 'Dmitry Rozhdestvenskiy <yellowmegaman@gmail.com>'
description: 'gha k3s'
branding:
  icon: 'aperture'
  color: 'yellow'
inputs:
  k3s_tag:
    description: "k3s tag to use"
    required: false
    default: 'v1.17.4-k3s1'
  custom_registry:
    description: "whenever to use registries.yaml in your repo or not"
    required: true
  parent_workspace:
    description: "this value is used to mount your registries.yaml file"
    required: false
    default: ${{github.workspace}}
  kubectl_version:
    description: "kubectl version to use"
    required: false
    default: "v1.18.1"
  install_kubectl:
    description: "whenever to copy kubectl to runner workspace"
    required: false
    default: "true"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - KUBECTL_VERSION: ${{inputs.kubectl_version}}
